/** @file   include/dmlite/common/config.h
 *  @brief  Header generated by CMake with the build configuration used.
 *  @author Automated generation
 */
#ifndef DMLITE_COMMON_CONFIG_H
#define DMLITE_COMMON_CONFIG_H

/* Version */
#define DMLITE_MAJOR @dmlite_MAJOR@
#define DMLITE_MINOR @dmlite_MINOR@
#define DMLITE_PATCH @dmlite_PATCH@

/* Use 64 bits types */
#ifndef __USE_LARGEFILE64
#  define __USE_LARGEFILE64
#endif
#ifndef _FILE_OFFSET_BITS
#  define _FILE_OFFSET_BITS 64
#endif
#ifndef __USE_FILE_OFFSET64
#  define __USE_FILE_OFFSET64
#endif

#endif /* DMLITE_COMMON_CONFIG_H */
