/** @file   include/dmlite/common/config.h
 *  @brief  Header generated by CMake with the build configuration used.
 *  @author Automated generation
 */
#ifndef DMLITE_COMMON_CONFIG_H
#define DMLITE_COMMON_CONFIG_H

/* Version */
#define DMLITE_MAJOR @dmlite_MAJOR@
#define DMLITE_MINOR @dmlite_MINOR@
#define DMLITE_PATCH @dmlite_PATCH@

/* 64 bits types must be used */
#if !defined(__x86_64__) && (_FILE_OFFSET_BITS != 64 || !defined(_LARGEFILE64_SOURCE))
#  error "You need to compile with -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE"
#endif

#endif /* DMLITE_COMMON_CONFIG_H */
