#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


function upgrade_stop_services () {
 echo "Stopping DPM services"
 service dpm-gsiftp stop 
 service srmv2.2 stop 
 service dpm stop 
 service dpnsdaemon stop
 service httpd stop
 service domehead stop
}

function upgrade_start_services () {
 echo "Starting up the DPM services"
 service dpnsdaemon start
 service dpm start
 service srmv2.2 start
 service dpm-gsiftp start
 service httpd start
 service domehead start
}

function upgrade () {

DPM_DB_HOST=$1
DPM_DB_USER=$2
DPM_DB_PASSWORD=$3
DPM_DB=$4
DPNS_DB=$5

# Gets the cns and dpm db's schema version
echo "Checking for database schema version... "

aux=`mysql --skip-column-names -s -h ${DPM_DB_HOST} -u ${DPM_DB_USER} --pass="${DPM_DB_PASSWORD}" -e "use ${DPM_DB}; select * from schema_version_dpm;" 2> /dev/null`
if [ $? -ne 0 ]; then
  echo "No DPM database schema version information found. Exiting."
  return 1
fi
dpmvdots=`echo $aux | awk '{print $1"."$2"."$3}'`
dpmv=`echo $aux | awk '{print $1$2$3}'`

aux=`mysql --skip-column-names -s -h ${DPM_DB_HOST} -u ${DPM_DB_USER} --pass="${DPM_DB_PASSWORD}" -e "use ${DPNS_DB}; select * from schema_version;" 2> /dev/null`
if [ $? -ne 0 ]; then
  echo "No DPNS database schema version information found. Exiting."
  return 1
fi
cnsvdots=`echo $aux | awk '{print $1"."$2"."$3}'`
cnsv=`echo $aux | awk '{print $1$2$3}'`

echo "Database versions used: DPM $dpmvdots - DPNS $cnsvdots"

# Good version?
if [ $dpmv -lt 340 ]; then
  echo "we only supports DPM database schema upgrade from versions 3.4.0 "
  echo "If you have schema version less then 3.4.0 , then please contact the support"
  return 1
fi

# Do we need to update?
ls /usr/share/dmlite/dbscripts/upgrade/dpm-db-$dpmv-* &> /dev/null
dpmupdate=$(($?==0))
ls /usr/share/dmlite/dbscripts/upgrade/cns-db-$cnsv-* &> /dev/null
cnsupdate=$(($?==0))
if [ $dpmupdate -ne 0 ] || [ $cnsupdate -ne 0 ]; then
  # Stop the services
  upgrade_stop_services

  # Store password
  passfile=`mktemp /tmp/dpm_upgrade.XXXXXX`
  echo "$DPM_DB_PASSWORD" > $passfile

  # Change working directory
  cd /usr/share/dmlite/dbscripts/upgrade/ &> /dev/null

  # Update DPM Schema
  for file in `ls dpm-db-*`
  do
    fromv=`echo $file | cut -d - -f 3`
    tov=`echo $file | cut -d - -f 5 | cut -d . -f 1`
    if [ $tov -gt $dpmv ]; then
      echo "Upgrading DPM schema from $fromv to $tov"
      /usr/bin/perl $file --db-vendor MySQL --db-host ${DPM_DB_HOST} --user ${DPM_DB_USER} --pwd-file ${passfile} --db ${DPM_DB} --verbose
      if [ $? -ne 0 ]; then
        echo "Error upgrading DPM schema"
	return 1
      fi
    fi
  done

  echo "DPM schema up to date"

  # Update DPNS Schema
  for file in `ls cns-db-*`
  do
    fromv=`echo $file | cut -d - -f 3`
    tov=`echo $file | cut -d - -f 5 | cut -d . -f 1`
    if [ $tov -gt $cnsv ]; then
      echo "Upgrading DPNS schema from $fromv to $tov"
      /usr/bin/perl $file --db-vendor MySQL --db-host ${DPM_DB_HOST} --user ${DPM_DB_USER} --pwd-file ${passfile} --db ${DPNS_DB} --verbose
      if [ $? -ne 0 ]; then
        echo "Error upgrading DPNS schema"
	return 1
      fi
    fi
  done

  echo "DPNS schema up to date"

  # Return to previous directory
  cd - &> /dev/null

  # Remove password
  rm -f ${passfile}

  # Restart
  upgrade_start_services
else
  echo "No upgrades needed"
fi
return 0
}


upgrade $1 $2 $3 $4 $5 
